[package]
cairo-version = "2.3.1"
description = "Implementations of a defi primitives for the Dojo framework"
name = "dojo_defi"
version = "0.3.3"

[lib]

[dependencies]
cubit = { git = "https://github.com/ponderingdemocritus/cubit" }
dojo = { git = "https://github.com/dojoengine/dojo", tag="nightly-bbdd5f22a8238cfa17212df217b339712e4e714c" }

[[target.dojo]]
